// Main menu structure. Items reference command ids; unregistered commands render disabled.
// Command id namespaces: file. edit. image. layer. type. select. filter. view. plugins. window. help.
import type { MenuEntry, MenuItem } from './menu';
import { app } from '../core/app';
import { isPanelVisible, WORKSPACES, dockState, customWorkspaces } from './dock';
import { panelDefs } from './panels';
import { commands } from '../core/commands';

const c = (label: string, cmd: string, shortcut?: string, arg?: any): MenuItem => ({ label, cmd, shortcut, arg });
const sub = (label: string, submenu: MenuEntry[] | (() => MenuEntry[])): MenuItem => ({ label, submenu });

const ADJUSTMENTS: MenuEntry[] = [
  c('Brightness/Contrast...', 'image.adjust', undefined, 'brightness-contrast'),
  c('Levels...', 'image.adjust', 'Ctrl+L', 'levels'),
  c('Curves...', 'image.adjust', 'Ctrl+M', 'curves'),
  c('Exposure...', 'image.adjust', undefined, 'exposure'),
  '-',
  c('Vibrance...', 'image.adjust', undefined, 'vibrance'),
  c('Hue/Saturation...', 'image.adjust', 'Ctrl+U', 'hue-saturation'),
  c('Color Balance...', 'image.adjust', 'Ctrl+B', 'color-balance'),
  c('Black & White...', 'image.adjust', 'Alt+Shift+Ctrl+B', 'black-white'),
  c('Photo Filter...', 'image.adjust', undefined, 'photo-filter'),
  c('Channel Mixer...', 'image.adjust', undefined, 'channel-mixer'),
  c('Color Lookup...', 'image.adjust', undefined, 'color-lookup'),
  '-',
  c('Invert', 'image.adjust', 'Ctrl+I', 'invert'),
  c('Posterize...', 'image.adjust', undefined, 'posterize'),
  c('Threshold...', 'image.adjust', undefined, 'threshold'),
  c('Gradient Map...', 'image.adjust', undefined, 'gradient-map'),
  c('Selective Color...', 'image.adjust', undefined, 'selective-color'),
  '-',
  c('Shadows/Highlights...', 'image.adjust', undefined, 'shadows-highlights'),
  c('HDR Toning...', 'image.adjust', undefined, 'hdr-toning'),
  '-',
  c('Desaturate', 'image.adjust', 'Shift+Ctrl+U', 'desaturate'),
  c('Match Color...', 'image.adjust', undefined, 'match-color'),
  c('Replace Color...', 'image.adjust', undefined, 'replace-color'),
  c('Equalize', 'image.adjust', undefined, 'equalize'),
];
const NEW_ADJ_LAYER: MenuEntry[] = [
  c('Brightness/Contrast...', 'layer.newAdjustment', undefined, 'brightness-contrast'),
  c('Levels...', 'layer.newAdjustment', undefined, 'levels'),
  c('Curves...', 'layer.newAdjustment', undefined, 'curves'),
  c('Exposure...', 'layer.newAdjustment', undefined, 'exposure'),
  '-',
  c('Vibrance...', 'layer.newAdjustment', undefined, 'vibrance'),
  c('Hue/Saturation...', 'layer.newAdjustment', undefined, 'hue-saturation'),
  c('Color Balance...', 'layer.newAdjustment', undefined, 'color-balance'),
  c('Black & White...', 'layer.newAdjustment', undefined, 'black-white'),
  c('Photo Filter...', 'layer.newAdjustment', undefined, 'photo-filter'),
  c('Channel Mixer...', 'layer.newAdjustment', undefined, 'channel-mixer'),
  c('Color Lookup...', 'layer.newAdjustment', undefined, 'color-lookup'),
  '-',
  c('Invert...', 'layer.newAdjustment', undefined, 'invert'),
  c('Posterize...', 'layer.newAdjustment', undefined, 'posterize'),
  c('Threshold...', 'layer.newAdjustment', undefined, 'threshold'),
  c('Gradient Map...', 'layer.newAdjustment', undefined, 'gradient-map'),
  c('Selective Color...', 'layer.newAdjustment', undefined, 'selective-color'),
];
const EFFECTS: [string, string][] = [
  ['Bevel & Emboss...', 'bevelEmboss'], ['Stroke...', 'stroke'], ['Inner Shadow...', 'innerShadow'], ['Inner Glow...', 'innerGlow'],
  ['Satin...', 'satin'], ['Color Overlay...', 'colorOverlay'], ['Gradient Overlay...', 'gradientOverlay'], ['Pattern Overlay...', 'patternOverlay'],
  ['Outer Glow...', 'outerGlow'], ['Drop Shadow...', 'dropShadow'],
];

/** Photoshop's panel list for the Window menu: [label, panel id, shortcut]. */
export const WINDOW_PANELS: [string, string, string?][] = [
  ['Actions', 'actions', 'Alt+F9'], ['Adjustments', 'adjustments'], ['Brush Settings', 'brush-settings', 'F5'], ['Brushes', 'brushes'],
  ['Channels', 'channels'], ['Character', 'character'], ['Character Styles', 'character-styles'], ['Clone Source', 'clone-source'],
  ['Color', 'color', 'F6'], ['Comments', 'comments'], ['Glyphs', 'glyphs'], ['Gradients', 'gradients'], ['Histogram', 'histogram'],
  ['History', 'history'], ['Info', 'info', 'F8'], ['Layer Comps', 'layer-comps'], ['Layers', 'layers', 'F7'], ['Learn', 'learn'],
  ['Libraries', 'libraries'], ['Measurement Log', 'measurement'], ['Navigator', 'navigator'], ['Notes', 'notes'], ['Paragraph', 'paragraph'],
  ['Paragraph Styles', 'paragraph-styles'], ['Paths', 'paths'], ['Patterns', 'patterns'], ['Properties', 'properties'], ['Shapes', 'shapes'],
  ['Styles', 'styles'], ['Swatches', 'swatches'], ['Timeline', 'timeline'], ['Tool Presets', 'tool-presets'],
];

export function buildMenus(): { label: string; items: () => MenuEntry[] }[] {
  return [
    {
      label: 'File', items: () => [
        c('New...', 'file.new', 'Ctrl+N'),
        c('Open...', 'file.open', 'Ctrl+O'),
        c('Open As...', 'file.openAs', 'Alt+Shift+Ctrl+O'),
        c('Open as Smart Object...', 'file.openAsSmart'),
        sub('Open Recent', () => (commands.get('file.recentList')?.run() as MenuEntry[]) || [{ label: '(No recent files)', enabled: false }]),
        '-',
        c('Close', 'file.close', 'Ctrl+W'),
        c('Close All', 'file.closeAll', 'Alt+Ctrl+W'),
        c('Close Others', 'file.closeOthers', 'Alt+Ctrl+P'),
        c('Save', 'file.save', 'Ctrl+S'),
        c('Save As...', 'file.saveAs', 'Shift+Ctrl+S'),
        c('Save a Copy...', 'file.saveCopy', 'Alt+Ctrl+S'),
        c('Revert', 'file.revert', 'F12'),
        '-',
        sub('Export', [
          c('Quick Export as PNG', 'file.quickExport', 'Shift+Ctrl+\''),
          c('Export As...', 'file.exportAs', 'Alt+Shift+Ctrl+W'),
          '-',
          c('Save for Web (Legacy)...', 'file.saveForWeb', 'Alt+Shift+Ctrl+S'),
          '-',
          c('Layers to Files...', 'file.layersToFiles'),
          c('Export as PSD...', 'file.exportPSD'),
        ]),
        '-',
        c('Place Embedded...', 'file.placeEmbedded'),
        c('Place Linked...', 'file.placeLinked'),
        '-',
        sub('Automate', [c('Batch...', 'file.batch'), c('Contact Sheet II...', 'file.contactSheet'), c('Crop and Straighten Photos', 'file.cropStraighten'), c('Fit Image...', 'file.fitImage')]),
        sub('Scripts', [c('Image Processor...', 'file.imageProcessor'), c('Load Files into Stack...', 'file.loadStack')]),
        sub('Import', [c('Images from Clipboard', 'file.importClipboard'), c('Images from Device...', 'file.importDevice')]),
        '-',
        c('File Info...', 'file.info', 'Alt+Shift+Ctrl+I'),
        '-',
        c('Print...', 'file.print', 'Ctrl+P'),
        c('Print One Copy', 'file.printOne', 'Alt+Shift+Ctrl+P'),
        '-',
        c('Exit', 'file.exit', 'Ctrl+Q'),
      ],
    },
    {
      label: 'Edit', items: () => {
        const d = app.activeDoc, h = d?.history;
        const undoName = h && h.canUndo ? h.entries[h.index - 1].name : '';
        const redoName = h && h.canRedo ? h.entries[h.index].name : '';
        return [
          c(undoName ? `Undo ${undoName}` : 'Undo', 'edit.undo', 'Ctrl+Z'),
          c(redoName ? `Redo ${redoName}` : 'Redo', 'edit.redo', 'Shift+Ctrl+Z'),
          c('Toggle Last State', 'edit.toggleLast', 'Alt+Ctrl+Z'),
          '-',
          c('Fade...', 'edit.fade', 'Shift+Ctrl+F'),
          '-',
          c('Cut', 'edit.cut', 'Ctrl+X'),
          c('Copy', 'edit.copy', 'Ctrl+C'),
          c('Copy Merged', 'edit.copyMerged', 'Shift+Ctrl+C'),
          c('Paste', 'edit.paste', 'Ctrl+V'),
          sub('Paste Special', [c('Paste in Place', 'edit.pasteInPlace', 'Shift+Ctrl+V'), c('Paste Into', 'edit.pasteInto', 'Alt+Shift+Ctrl+V'), c('Paste Outside', 'edit.pasteOutside')]),
          c('Clear', 'edit.clear', 'Delete'),
          '-',
          c('Search', 'edit.search', 'Ctrl+F'),
          c('Check Spelling...', 'type.checkSpelling'),
          c('Find and Replace Text...', 'type.findReplace'),
          '-',
          c('Fill...', 'edit.fill', 'Shift+F5'),
          c('Stroke...', 'edit.stroke'),
          c('Content-Aware Fill...', 'edit.contentAwareFill'),
          '-',
          c('Content-Aware Scale', 'edit.contentAwareScale', 'Alt+Shift+Ctrl+C'),
          c('Puppet Warp', 'edit.puppetWarp'),
          c('Perspective Warp', 'edit.perspectiveWarp'),
          c('Free Transform', 'edit.freeTransform', 'Ctrl+T'),
          sub('Transform', [
            c('Again', 'edit.transformAgain', 'Shift+Ctrl+T'),
            '-',
            c('Scale', 'edit.transform', undefined, 'scale'), c('Rotate', 'edit.transform', undefined, 'rotate'), c('Skew', 'edit.transform', undefined, 'skew'),
            c('Distort', 'edit.transform', undefined, 'distort'), c('Perspective', 'edit.transform', undefined, 'perspective'), c('Warp', 'edit.transform', undefined, 'warp'),
            '-',
            c('Rotate 180°', 'edit.transform', undefined, 'rotate180'), c('Rotate 90° Clockwise', 'edit.transform', undefined, 'rotate90cw'), c('Rotate 90° Counter Clockwise', 'edit.transform', undefined, 'rotate90ccw'),
            '-',
            c('Flip Horizontal', 'edit.transform', undefined, 'flipH'), c('Flip Vertical', 'edit.transform', undefined, 'flipV'),
          ]),
          c('Auto-Align Layers...', 'edit.autoAlign'),
          c('Auto-Blend Layers...', 'edit.autoBlend'),
          c('Sky Replacement...', 'edit.skyReplacement'),
          '-',
          c('Define Brush Preset...', 'edit.defineBrush'),
          c('Define Pattern...', 'edit.definePattern'),
          c('Define Custom Shape...', 'edit.defineShape'),
          '-',
          sub('Purge', [c('Clipboard', 'edit.purge', undefined, 'clipboard'), c('Histories', 'edit.purge', undefined, 'histories'), c('All', 'edit.purge', undefined, 'all')]),
          '-',
          sub('Presets', [c('Preset Manager...', 'edit.presetManager'), c('Export/Import Presets...', 'edit.exportPresets')]),
          '-',
          c('Color Settings...', 'edit.colorSettings', 'Shift+Ctrl+K'),
          c('Assign Profile...', 'edit.assignProfile'),
          c('Convert to Profile...', 'edit.convertProfile'),
          '-',
          c('Keyboard Shortcuts...', 'edit.keyboardShortcuts', 'Alt+Shift+Ctrl+K'),
          c('Menus...', 'edit.menus', 'Alt+Shift+Ctrl+M'),
          c('Toolbar...', 'edit.toolbar'),
          sub('Preferences', [
            c('General...', 'edit.preferences', 'Ctrl+K', 'general'), c('Interface...', 'edit.preferences', undefined, 'interface'),
            c('Workspace...', 'edit.preferences', undefined, 'workspace'), c('Tools...', 'edit.preferences', undefined, 'tools'),
            c('History Log...', 'edit.preferences', undefined, 'history'), c('File Handling...', 'edit.preferences', undefined, 'files'),
            c('Export...', 'edit.preferences', undefined, 'export'), c('Performance...', 'edit.preferences', undefined, 'performance'),
            c('Cursors...', 'edit.preferences', undefined, 'cursors'), c('Transparency & Gamut...', 'edit.preferences', undefined, 'transparency'),
            c('Units & Rulers...', 'edit.preferences', undefined, 'units'), c('Guides, Grid & Slices...', 'edit.preferences', undefined, 'guides'),
            c('Plugins...', 'edit.preferences', undefined, 'plugins'), c('Type...', 'edit.preferences', undefined, 'type'),
            c('Technology Previews...', 'edit.preferences', undefined, 'tech'),
          ]),
        ];
      },
    },
    {
      label: 'Image', items: () => [
        sub('Mode', [
          c('Bitmap...', 'image.mode', undefined, 'Bitmap'), c('Grayscale', 'image.mode', undefined, 'Grayscale'), c('Duotone...', 'image.mode', undefined, 'Duotone'),
          c('Indexed Color...', 'image.mode', undefined, 'Indexed'), { label: 'RGB Color', cmd: 'image.mode', arg: 'RGB', checked: () => app.activeDoc?.mode === 'RGB' },
          c('CMYK Color', 'image.mode', undefined, 'CMYK'), c('Lab Color', 'image.mode', undefined, 'Lab'), c('Multichannel', 'image.mode', undefined, 'Multichannel'),
          '-',
          { label: '8 Bits/Channel', cmd: 'image.bitDepth', arg: 8, checked: () => app.activeDoc?.bitDepth === 8 },
          { label: '16 Bits/Channel', cmd: 'image.bitDepth', arg: 16, checked: () => app.activeDoc?.bitDepth === 16 },
          { label: '32 Bits/Channel', cmd: 'image.bitDepth', arg: 32, checked: () => app.activeDoc?.bitDepth === 32 },
          '-',
          c('Color Table...', 'image.colorTable'),
        ]),
        '-',
        sub('Adjustments', ADJUSTMENTS),
        '-',
        c('Auto Tone', 'image.autoTone', 'Shift+Ctrl+L'),
        c('Auto Contrast', 'image.autoContrast', 'Alt+Shift+Ctrl+L'),
        c('Auto Color', 'image.autoColor', 'Shift+Ctrl+B'),
        '-',
        c('Image Size...', 'image.imageSize', 'Alt+Ctrl+I'),
        c('Canvas Size...', 'image.canvasSize', 'Alt+Ctrl+C'),
        sub('Image Rotation', [
          c('180°', 'image.rotate', undefined, 180), c('90° Clockwise', 'image.rotate', undefined, 90), c('90° Counter Clockwise', 'image.rotate', undefined, -90),
          c('Arbitrary...', 'image.rotateArbitrary'),
          '-',
          c('Flip Canvas Horizontal', 'image.flip', undefined, 'h'), c('Flip Canvas Vertical', 'image.flip', undefined, 'v'),
        ]),
        c('Crop', 'image.crop'),
        c('Trim...', 'image.trim'),
        c('Reveal All', 'image.revealAll'),
        '-',
        c('Duplicate...', 'image.duplicate'),
        c('Apply Image...', 'image.applyImage'),
        c('Calculations...', 'image.calculations'),
        '-',
        sub('Variables', [c('Define...', 'image.variables'), c('Data Sets...', 'image.dataSets')]),
        c('Apply Data Set...', 'image.applyDataSet'),
        '-',
        c('Trap...', 'image.trap'),
        '-',
        sub('Analysis', [c('Set Measurement Scale...', 'image.measureScale'), c('Record Measurements', 'image.recordMeasurements'), '-', c('Ruler Tool', 'image.rulerTool'), c('Count Tool', 'image.countTool')]),
      ],
    },
    {
      label: 'Layer', items: () => [
        sub('New', [
          c('Layer...', 'layer.new', 'Shift+Ctrl+N'),
          c('Background from Layer', 'layer.backgroundFromLayer'),
          c('Layer from Background...', 'layer.layerFromBackground'),
          '-',
          c('Group...', 'layer.newGroup'),
          c('Group from Layers...', 'layer.groupFromLayers'),
          c('Artboard...', 'layer.newArtboard'),
          '-',
          c('Layer via Copy', 'layer.viaCopy', 'Ctrl+J'),
          c('Layer via Cut', 'layer.viaCut', 'Shift+Ctrl+J'),
        ]),
        c('Copy CSS', 'layer.copyCSS'),
        c('Copy SVG', 'layer.copySVG'),
        c('Duplicate Layer...', 'layer.duplicate'),
        sub('Delete', [c('Layer', 'layer.delete'), c('Hidden Layers', 'layer.deleteHidden')]),
        c('Quick Export as PNG', 'layer.quickExport'),
        c('Export As...', 'layer.exportAs'),
        '-',
        c('Rename Layer...', 'layer.rename'),
        sub('Layer Style', [
          c('Blending Options...', 'layer.style', undefined, 'blending'),
          '-',
          ...EFFECTS.map(([l, t]) => c(l, 'layer.style', undefined, t)),
          '-',
          c('Copy Layer Style', 'layer.copyStyle'), c('Paste Layer Style', 'layer.pasteStyle'), c('Clear Layer Style', 'layer.clearStyle'),
          '-',
          c('Global Light...', 'layer.globalLight'), c('Create Layer', 'layer.styleToLayers'), c('Hide All Effects', 'layer.hideAllEffects'), c('Scale Effects...', 'layer.scaleEffects'),
        ]),
        sub('Smart Filter', [c('Disable Smart Filters', 'layer.smartFilterToggle'), c('Clear Smart Filters', 'layer.smartFilterClear')]),
        '-',
        sub('New Fill Layer', [c('Solid Color...', 'layer.newFill', undefined, 'solid'), c('Gradient...', 'layer.newFill', undefined, 'gradient'), c('Pattern...', 'layer.newFill', undefined, 'pattern')]),
        sub('New Adjustment Layer', NEW_ADJ_LAYER),
        c('Layer Content Options...', 'layer.contentOptions'),
        '-',
        sub('Layer Mask', [
          c('Reveal All', 'layer.mask', undefined, 'revealAll'), c('Hide All', 'layer.mask', undefined, 'hideAll'),
          c('Reveal Selection', 'layer.mask', undefined, 'revealSelection'), c('Hide Selection', 'layer.mask', undefined, 'hideSelection'),
          c('From Transparency', 'layer.mask', undefined, 'fromTransparency'),
          '-',
          c('Delete', 'layer.mask', undefined, 'delete'), c('Apply', 'layer.mask', undefined, 'apply'),
          '-',
          c('Disable', 'layer.mask', undefined, 'toggle'), c('Unlink', 'layer.mask', undefined, 'unlink'),
        ]),
        sub('Vector Mask', [c('Reveal All', 'layer.vectorMask', undefined, 'revealAll'), c('Hide All', 'layer.vectorMask', undefined, 'hideAll'), c('Current Path', 'layer.vectorMask', undefined, 'currentPath'), '-', c('Delete', 'layer.vectorMask', undefined, 'delete')]),
        c('Create Clipping Mask', 'layer.clippingMask', 'Alt+Ctrl+G'),
        '-',
        sub('Smart Objects', [
          c('Convert to Smart Object', 'layer.toSmartObject'), c('New Smart Object via Copy', 'layer.smartViaCopy'),
          c('Edit Contents', 'layer.smartEdit'), c('Export Contents...', 'layer.smartExport'), c('Replace Contents...', 'layer.smartReplace'),
          '-', c('Rasterize', 'layer.rasterize', undefined, 'smart'),
        ]),
        sub('Rasterize', [
          c('Type', 'layer.rasterize', undefined, 'type'), c('Shape', 'layer.rasterize', undefined, 'shape'), c('Fill Content', 'layer.rasterize', undefined, 'fill'),
          c('Vector Mask', 'layer.rasterize', undefined, 'vectorMask'), c('Smart Object', 'layer.rasterize', undefined, 'smart'),
          '-', c('Layer', 'layer.rasterize', undefined, 'layer'), c('All Layers', 'layer.rasterize', undefined, 'all'), c('Layer Style', 'layer.rasterize', undefined, 'style'),
        ]),
        '-',
        c('Group Layers', 'layer.group', 'Ctrl+G'),
        c('Ungroup Layers', 'layer.ungroup', 'Shift+Ctrl+G'),
        c('Hide Layers', 'layer.hide', 'Ctrl+,'),
        '-',
        sub('Arrange', [
          c('Bring to Front', 'layer.arrange', 'Shift+Ctrl+]', 'front'), c('Bring Forward', 'layer.arrange', 'Ctrl+]', 'forward'),
          c('Send Backward', 'layer.arrange', 'Ctrl+[', 'backward'), c('Send to Back', 'layer.arrange', 'Shift+Ctrl+[', 'back'),
          '-', c('Reverse', 'layer.arrange', undefined, 'reverse'),
        ]),
        '-',
        sub('Align', [
          c('Top Edges', 'layer.align', undefined, 'top'), c('Vertical Centers', 'layer.align', undefined, 'vcenter'), c('Bottom Edges', 'layer.align', undefined, 'bottom'),
          '-',
          c('Left Edges', 'layer.align', undefined, 'left'), c('Horizontal Centers', 'layer.align', undefined, 'hcenter'), c('Right Edges', 'layer.align', undefined, 'right'),
        ]),
        sub('Distribute', [
          c('Top Edges', 'layer.distribute', undefined, 'top'), c('Vertical Centers', 'layer.distribute', undefined, 'vcenter'), c('Bottom Edges', 'layer.distribute', undefined, 'bottom'),
          '-',
          c('Left Edges', 'layer.distribute', undefined, 'left'), c('Horizontal Centers', 'layer.distribute', undefined, 'hcenter'), c('Right Edges', 'layer.distribute', undefined, 'right'),
        ]),
        '-',
        c('Lock Layers...', 'layer.lockDialog', 'Ctrl+/'),
        '-',
        c('Link Layers', 'layer.link'),
        c('Select Linked Layers', 'layer.selectLinked'),
        '-',
        c(app.activeDoc && app.activeDoc.selectedIds.length > 1 ? 'Merge Layers' : 'Merge Down', 'layer.mergeDown', 'Ctrl+E'),
        c('Merge Visible', 'layer.mergeVisible', 'Shift+Ctrl+E'),
        c('Flatten Image', 'layer.flatten'),
        '-',
        sub('Matting', [c('Color Decontaminate', 'layer.matting', undefined, 'decontaminate'), c('Defringe...', 'layer.matting', undefined, 'defringe'), c('Remove Black Matte', 'layer.matting', undefined, 'black'), c('Remove White Matte', 'layer.matting', undefined, 'white')]),
      ],
    },
    {
      label: 'Type', items: () => [
        c('More Fonts...', 'type.moreFonts'),
        sub('Panels', [c('Character Panel', 'window.togglePanel', undefined, 'character'), c('Paragraph Panel', 'window.togglePanel', undefined, 'paragraph'), c('Glyphs Panel', 'window.togglePanel', undefined, 'glyphs'), c('Character Styles Panel', 'window.togglePanel', undefined, 'character-styles'), c('Paragraph Styles Panel', 'window.togglePanel', undefined, 'paragraph-styles')]),
        sub('Anti-Alias', [c('None', 'type.antialias', undefined, 'none'), c('Sharp', 'type.antialias', undefined, 'sharp'), c('Crisp', 'type.antialias', undefined, 'crisp'), c('Strong', 'type.antialias', undefined, 'strong'), c('Smooth', 'type.antialias', undefined, 'smooth')]),
        sub('Orientation', [c('Horizontal', 'type.orientation', undefined, 'horizontal'), c('Vertical', 'type.orientation', undefined, 'vertical')]),
        '-',
        c('Create Work Path', 'type.createWorkPath'),
        c('Convert to Shape', 'type.convertToShape'),
        c('Rasterize Type Layer', 'layer.rasterize', undefined, 'type'),
        '-',
        c('Convert to Paragraph Text', 'type.convertParagraph'),
        c('Warp Text...', 'type.warp'),
        c('Match Font...', 'type.matchFont'),
        sub('Font Preview Size', [c('Small', 'type.previewSize', undefined, 'small'), c('Medium', 'type.previewSize', undefined, 'medium'), c('Large', 'type.previewSize', undefined, 'large')]),
        '-',
        c('Update All Text Layers', 'type.updateAll'),
        c('Paste Lorem Ipsum', 'type.loremIpsum'),
      ],
    },
    {
      label: 'Select', items: () => [
        c('All', 'select.all', 'Ctrl+A'),
        c('Deselect', 'select.deselect', 'Ctrl+D'),
        c('Reselect', 'select.reselect', 'Shift+Ctrl+D'),
        c('Inverse', 'select.inverse', 'Shift+Ctrl+I'),
        '-',
        c('All Layers', 'select.allLayers', 'Alt+Ctrl+A'),
        c('Deselect Layers', 'select.deselectLayers'),
        c('Find Layers', 'select.findLayers', 'Alt+Shift+Ctrl+F'),
        c('Isolate Layers', 'select.isolateLayers'),
        '-',
        c('Color Range...', 'select.colorRange'),
        c('Focus Area...', 'select.focusArea'),
        c('Subject', 'select.subject'),
        c('Sky', 'select.sky'),
        '-',
        c('Select and Mask...', 'select.selectAndMask', 'Alt+Ctrl+R'),
        sub('Modify', [c('Border...', 'select.modify', undefined, 'border'), c('Smooth...', 'select.modify', undefined, 'smooth'), c('Expand...', 'select.modify', undefined, 'expand'), c('Contract...', 'select.modify', undefined, 'contract'), c('Feather...', 'select.modify', 'Shift+F6', 'feather')]),
        '-',
        c('Grow', 'select.grow'),
        c('Similar', 'select.similar'),
        '-',
        c('Transform Selection', 'select.transform'),
        '-',
        c('Edit in Quick Mask Mode', 'select.quickMask', 'Q'),
        '-',
        c('Load Selection...', 'select.load'),
        c('Save Selection...', 'select.save'),
      ],
    },
    {
      label: 'Filter', items: () => [
        c(commands.get('filter.last')?.label || 'Last Filter', 'filter.last', 'Alt+Ctrl+F'),
        '-',
        c('Convert for Smart Filters', 'filter.convertSmart'),
        '-',
        c('Neural Filters...', 'filter.neural'),
        c('Filter Gallery...', 'filter.gallery'),
        c('Adaptive Wide Angle...', 'filter.adaptiveWideAngle', 'Alt+Shift+Ctrl+A'),
        c('Camera Raw Filter...', 'filter.cameraRaw', 'Shift+Ctrl+A'),
        c('Lens Correction...', 'filter.lensCorrection', 'Shift+Ctrl+R'),
        c('Liquify...', 'filter.liquify', 'Shift+Ctrl+X'),
        c('Vanishing Point...', 'filter.vanishingPoint', 'Alt+Ctrl+V'),
        '-',
        sub('Blur', [
          c('Average', 'filter.run', undefined, 'average'), c('Blur', 'filter.run', undefined, 'blur'), c('Blur More', 'filter.run', undefined, 'blur-more'),
          c('Box Blur...', 'filter.run', undefined, 'box-blur'), c('Gaussian Blur...', 'filter.run', undefined, 'gaussian-blur'), c('Lens Blur...', 'filter.run', undefined, 'lens-blur'),
          c('Motion Blur...', 'filter.run', undefined, 'motion-blur'), c('Radial Blur...', 'filter.run', undefined, 'radial-blur'), c('Shape Blur...', 'filter.run', undefined, 'shape-blur'),
          c('Smart Blur...', 'filter.run', undefined, 'smart-blur'), c('Surface Blur...', 'filter.run', undefined, 'surface-blur'),
        ]),
        sub('Blur Gallery', [c('Field Blur...', 'filter.run', undefined, 'field-blur'), c('Iris Blur...', 'filter.run', undefined, 'iris-blur'), c('Tilt-Shift...', 'filter.run', undefined, 'tilt-shift'), c('Path Blur...', 'filter.run', undefined, 'path-blur'), c('Spin Blur...', 'filter.run', undefined, 'spin-blur')]),
        sub('Distort', [
          c('Displace...', 'filter.run', undefined, 'displace'), c('Pinch...', 'filter.run', undefined, 'pinch'), c('Polar Coordinates...', 'filter.run', undefined, 'polar'),
          c('Ripple...', 'filter.run', undefined, 'ripple'), c('Shear...', 'filter.run', undefined, 'shear'), c('Spherize...', 'filter.run', undefined, 'spherize'),
          c('Twirl...', 'filter.run', undefined, 'twirl'), c('Wave...', 'filter.run', undefined, 'wave'), c('ZigZag...', 'filter.run', undefined, 'zigzag'),
        ]),
        sub('Noise', [c('Add Noise...', 'filter.run', undefined, 'add-noise'), c('Despeckle', 'filter.run', undefined, 'despeckle'), c('Dust & Scratches...', 'filter.run', undefined, 'dust-scratches'), c('Median...', 'filter.run', undefined, 'median'), c('Reduce Noise...', 'filter.run', undefined, 'reduce-noise')]),
        sub('Pixelate', [c('Color Halftone...', 'filter.run', undefined, 'color-halftone'), c('Crystallize...', 'filter.run', undefined, 'crystallize'), c('Facet', 'filter.run', undefined, 'facet'), c('Fragment', 'filter.run', undefined, 'fragment'), c('Mezzotint...', 'filter.run', undefined, 'mezzotint'), c('Mosaic...', 'filter.run', undefined, 'mosaic'), c('Pointillize...', 'filter.run', undefined, 'pointillize')]),
        sub('Render', [c('Flame...', 'filter.run', undefined, 'flame'), c('Picture Frame...', 'filter.run', undefined, 'picture-frame'), c('Tree...', 'filter.run', undefined, 'tree'), '-', c('Clouds', 'filter.run', undefined, 'clouds'), c('Difference Clouds', 'filter.run', undefined, 'difference-clouds'), c('Fibers...', 'filter.run', undefined, 'fibers'), c('Lens Flare...', 'filter.run', undefined, 'lens-flare'), c('Lighting Effects...', 'filter.run', undefined, 'lighting')]),
        sub('Sharpen', [c('Shake Reduction...', 'filter.run', undefined, 'shake-reduction'), c('Sharpen', 'filter.run', undefined, 'sharpen'), c('Sharpen Edges', 'filter.run', undefined, 'sharpen-edges'), c('Sharpen More', 'filter.run', undefined, 'sharpen-more'), c('Smart Sharpen...', 'filter.run', undefined, 'smart-sharpen'), c('Unsharp Mask...', 'filter.run', undefined, 'unsharp-mask')]),
        sub('Stylize', [c('Diffuse...', 'filter.run', undefined, 'diffuse'), c('Emboss...', 'filter.run', undefined, 'emboss'), c('Extrude...', 'filter.run', undefined, 'extrude'), c('Find Edges', 'filter.run', undefined, 'find-edges'), c('Oil Paint...', 'filter.run', undefined, 'oil-paint'), c('Solarize', 'filter.run', undefined, 'solarize'), c('Tiles...', 'filter.run', undefined, 'tiles'), c('Trace Contour...', 'filter.run', undefined, 'trace-contour'), c('Wind...', 'filter.run', undefined, 'wind')]),
        sub('Video', [c('De-Interlace...', 'filter.run', undefined, 'deinterlace'), c('NTSC Colors', 'filter.run', undefined, 'ntsc')]),
        sub('Other', [c('Custom...', 'filter.run', undefined, 'custom'), c('High Pass...', 'filter.run', undefined, 'high-pass'), c('HSB/HSL', 'filter.run', undefined, 'hsb-hsl'), c('Maximum...', 'filter.run', undefined, 'maximum'), c('Minimum...', 'filter.run', undefined, 'minimum'), c('Offset...', 'filter.run', undefined, 'offset')]),
      ],
    },
    {
      label: 'View', items: () => [
        c('Proof Colors', 'view.proofColors', 'Ctrl+Y'),
        c('Gamut Warning', 'view.gamutWarning', 'Shift+Ctrl+Y'),
        '-',
        c('Zoom In', 'view.zoomIn', 'Ctrl+='),
        c('Zoom Out', 'view.zoomOut', 'Ctrl+-'),
        c('Fit on Screen', 'view.fit', 'Ctrl+0'),
        c('Fill Screen', 'view.fill'),
        c('100%', 'view.actual', 'Ctrl+1'),
        c('200%', 'view.zoom200'),
        c('Print Size', 'view.printSize'),
        c('Flip Horizontal', 'view.flip'),
        c('Pattern Preview', 'view.patternPreview'),
        '-',
        sub('Screen Mode', [
          { label: 'Standard Screen Mode', cmd: 'view.screenMode', arg: 'standard', radio: true, checked: () => app.screenMode === 'standard' },
          { label: 'Full Screen Mode With Menu Bar', cmd: 'view.screenMode', arg: 'full-menu', radio: true, checked: () => app.screenMode === 'full-menu' },
          { label: 'Full Screen Mode', cmd: 'view.screenMode', arg: 'full', radio: true, checked: () => app.screenMode === 'full' },
        ]),
        '-',
        c('Extras', 'view.extras', 'Ctrl+H'),
        sub('Show', [
          c('Layer Edges', 'view.show', undefined, 'layerEdges'), c('Selection Edges', 'view.show', undefined, 'selectionEdges'), c('Target Path', 'view.show', 'Shift+Ctrl+H', 'targetPath'),
          c('Grid', 'view.show', 'Ctrl+\'', 'grid'), c('Guides', 'view.show', 'Ctrl+;', 'guides'), c('Count', 'view.show', undefined, 'count'),
          c('Smart Guides', 'view.show', undefined, 'smartGuides'), c('Notes', 'view.show', undefined, 'notes'), c('Pixel Grid', 'view.show', undefined, 'pixelGrid'),
          '-', c('All', 'view.show', undefined, 'all'), c('None', 'view.show', undefined, 'none'),
        ]),
        '-',
        c('Rulers', 'view.rulers', 'Ctrl+R'),
        '-',
        c('Snap', 'view.snap', 'Shift+Ctrl+;'),
        sub('Snap To', [c('Guides', 'view.snapTo', undefined, 'snapGuides'), c('Grid', 'view.snapTo', undefined, 'snapGrid'), c('Layers', 'view.snapTo', undefined, 'snapLayers'), c('Document Bounds', 'view.snapTo', undefined, 'snapBounds'), '-', c('All', 'view.snapTo', undefined, 'all'), c('None', 'view.snapTo', undefined, 'none')]),
        '-',
        sub('Guides', [c('Lock Guides', 'view.lockGuides', 'Alt+Ctrl+;'), c('Clear Guides', 'view.clearGuides'), '-', c('New Guide...', 'view.newGuide'), c('New Guide Layout...', 'view.newGuideLayout'), c('New Guides From Shape', 'view.guidesFromShape')]),
        '-',
        c('Lock Slices', 'view.lockSlices'),
        c('Clear Slices', 'view.clearSlices'),
      ],
    },
    {
      label: 'Plugins', items: () => [
        c('Plugins Panel', 'plugins.panel'),
        c('Browse Plugins...', 'plugins.browse'),
        c('Manage Plugins...', 'plugins.manage'),
        '-',
        ...((commands.get('plugins.list')?.run() as MenuEntry[]) || []),
      ],
    },
    {
      label: 'Window', items: () => [
        sub('Arrange', [
          c('Tile All Vertically', 'window.arrange', undefined, 'tile-v'), c('Tile All Horizontally', 'window.arrange', undefined, 'tile-h'),
          c('2-up Vertical', 'window.arrange', undefined, '2up-v'), c('2-up Horizontal', 'window.arrange', undefined, '2up-h'),
          c('Consolidate All to Tabs', 'window.arrange', undefined, 'tabs'),
          '-',
          c('Float in Window', 'window.arrange', undefined, 'float'), c('Float All in Windows', 'window.arrange', undefined, 'float-all'),
          '-',
          c('Match Zoom', 'window.match', undefined, 'zoom'), c('Match Location', 'window.match', undefined, 'location'), c('Match Rotation', 'window.match', undefined, 'rotation'), c('Match All', 'window.match', undefined, 'all'),
          '-',
          c(`New Window for ${app.activeDoc?.name || 'Document'}`, 'window.newWindow'),
        ]),
        sub('Workspace', () => [
          ...[...Object.keys(WORKSPACES)].map(n => ({ label: n === 'Essentials' ? 'Essentials (Default)' : n, cmd: 'window.workspace', arg: n, radio: true, checked: () => dockState.workspace === n })),
          '-',
          c(`Reset ${dockState.workspace}`, 'window.resetWorkspace'),
          c('New Workspace...', 'window.newWorkspace'),
          { label: 'Delete Workspace...', cmd: 'window.deleteWorkspace', enabled: customWorkspaces().length > 0 },
          '-',
          c('Keyboard Shortcuts & Menus...', 'edit.keyboardShortcuts'),
        ]),
        '-',
        ...WINDOW_PANELS.map(([label, id, sc]) => ({
          label, shortcut: sc, cmd: 'window.togglePanel', arg: id, enabled: panelDefs.has(id), checked: () => isPanelVisible(id),
        } as MenuItem)),
        '-',
        { label: 'Options', checked: () => !document.body.classList.contains('hide-options'), action: () => document.body.classList.toggle('hide-options') },
        { label: 'Tools', checked: () => !document.body.classList.contains('hide-tools'), action: () => document.body.classList.toggle('hide-tools') },
        '-',
        ...app.docs.map((d, i) => ({ label: `${i + 1} ${d.name}`, radio: true, checked: () => app.activeDoc === d, action: () => app.setActiveDocument(d) } as MenuItem)),
      ],
    },
    {
      label: 'Help', items: () => [
        c('Pixora Help...', 'help.help', 'F1'),
        c('Hands-on Tutorials...', 'help.tutorials'),
        c('Keyboard Shortcuts', 'help.shortcuts'),
        c("What's New", 'help.whatsNew'),
        '-',
        c('About Pixora...', 'help.about'),
        c('About Plugins...', 'help.aboutPlugins'),
        '-',
        c('System Info...', 'help.systemInfo'),
        c('GPU Compatibility...', 'help.gpu'),
        '-',
        c('Updates...', 'help.updates'),
      ],
    },
  ];
}
